FROM r-base:4.0.3

RUN apt-get update && apt-get install -y \
    default-jdk

RUN R -e "install.packages(c('xlsx', 'dplyr', 'e1071', 'caret', 'rpart', 'taRifx', 'stringr', 'rpart.plot'), \
                           dependencies = TRUE, \
                           repos = 'http://cran.rstudio.com/')"
